[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8jR5GeNzeweq35Uo84kGP3v1NcBaZWH5u62k7PxN4T2y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# We need '--test-reporter=spec' to get a more readable output on GitHub CI
# this has no effect on local runs
# We use '--no-warnings' to suppress warnings about Ed25519 being experimental in node.js
test = "npx tsx create-codama-client.ts; npx tsx --test --test-reporter=spec --no-warnings tests/*.ts"
