[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "qbuMdeYxYJXBjU6C6qFKjZKjXmrU83eDQomHdrch826"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Silence:
# "(node:23320) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead"
# web3.js v1 requires whatwg-url which uses this old library
# See https://stackoverflow.com/questions/68774489/punycode-is-deprecated-in-npm-what-should-i-replace-it-with
# TODO: Remove this once web3.js v2 is used
test = "npx esrun --node-no-warnings tests/*.ts"
