[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8jR5GeNzeweq35Uo84kGP3v1NcBaZWH5u62k7PxN4T2y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx create-codama-client.ts; npx tsx --test --no-warnings tests/*.ts"
