# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Builds and passes tests with 0 warnings or errors

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: metaDAOproject/setup-anchor@v3.1
        with:
          anchor-version: "0.31.1"
          solana-cli-version: "2.1.21"
          node-version: "22.14.0"

      # Fix for https://github.com/solana-foundation/anchor/issues/3596
      # TODO: Remove this once the issue is fixed
      - name: Manually download Anchor binary
        run: |
          npm i -g @coral-xyz/anchor-cli@0.31.2

      # git will keep outputting:
      #   hint: Using 'master' as the name for the initial branch. This default branch name
      #   hint: is subject to change.
      # Unless we set this.
      - name: Set a default branch name for git
        run: |
          git config --global init.defaultBranch main

      # Fixes:
      #   Error: Unable to read keypair file
      # during 'anchor test'
      # Hide the output of the command to avoid cluttering the logs
      - name: Make a default keypair
        run: |
          solana-keygen new --no-bip39-passphrase &> /dev/null

      # RUSTUP_TOOLCHAIN is needed for consistent builds per
      # https://solana.stackexchange.com/questions/21664/why-is-the-same-commit-of-an-anchor-repo-giving-different-results-when-run-at-di
      # TODO: remove when no longer necessary
      - name: Test the project builds and tests pass
        run: |
          echo "----------------------------------------"
          echo "Showing versions..."
          npm run show-versions
          echo "----------------------------------------"
          echo "Creating a keypair..."
          solana-keygen new --no-bip39-passphrase -s -o deleteme.json
          echo SECRET_KEY="$(cat deleteme.json)"> .env
          echo "----------------------------------------"
          echo "Installing packages..."
          npm i
          echo "----------------------------------------"
          echo "Running 'anchor test'..."
          export RUSTUP_TOOLCHAIN='nightly-2025-04-16'
          anchor test 2>&1 | tee -a build.log
          echo "----------------------------------------"
          echo "build.log..."
          cat build.log
          echo "----------------------------------------"
          echo "Checking for errors or warnings in build.log..."
          grep -qiEvz 'error:|warning:|failed' build.log
          echo $?
